version: '3'

tasks:
  install:
    sources:
      - pyproject.toml
      - uv.lock
    cmds:
      - uv sync
    dir: ./application
  
  dev:
    deps: [install]
    cmds:
      - cd {{.USER_WORKING_DIR}} && uv run {{.TASKFILE_DIR}}/run_api.py
  
  install-cli:
    deps: [install]
    cmds:
      - uv pip install -e .
  